---
title: "Data Cleaning"
author: "Eli Cohen, Sarah Tandean"
date: "2023-01-28"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
## Data initialization

# Drop KOs, Extra Pts, 2 Pt conversions, Penalties, and Timeouts
init.data.full = read.csv("Initial_Play_-_By_-_Play.csv", na=c(""))
KO.plays = c("KO", "KO Rec", "Onside Kick Rec")

# Fixing the Extra Points labeled as FGs
init.data.full[1442, "play.type"] = "Extra Pt."
init.data.full[1556, "play.type"] = "Extra Pt."
init.data.full[1975, "play.type"] = "Extra Pt."
init.data.full[1994, "play.type"] = "Extra Pt."

extra.pt.rows = which(init.data.full$PLAY.TYPE == "Extra Pt." |
                        init.data.full$PLAY.TYPE == "Extra Pt. Block")
KO.rows = which(init.data.full$PLAY.TYPE %in% KO.plays)
two.pt.rows = which(init.data.full$PLAY.TYPE == "2 Pt." | 
                      init.data.full$PLAY.TYPE == "2 Pt. Defend")
penalty.rows = which(init.data.full$RESULT == "Penalty")
timeout.rows = which(init.data.full$RESULT == "Timeout")

rem.rows = c(extra.pt.rows, KO.rows, two.pt.rows, penalty.rows, timeout.rows)
init.data = init.data.full[-rem.rows, ]

# Create possession team column
init.data$pos.team = ifelse(init.data$ODK == "O", "CMU", "Opp")

  # fill in missing values that shouldn't be missing
init.data[945, "ODK"] = "D"
init.data[955, "ODK"] = "D"
init.data[980, "ODK"] = "O"
init.data[1025, "ODK"] = "D"
init.data[1292, "ODK"] = "O"
init.data[1318, "ODK"] = "D"

for (i in 1:nrow(init.data)) {
  if (init.data[i, "ODK"] == "K") {
    init.data[i, "pos.team"] = init.data[i - 1, "pos.team"]
  }
}

# convert character variables to factor
#factor.vars = c("ODK", "RESULT", "PLAY.TYPE")
#init.data[factor.vars] = lapply(init.data[factor.vars], factor)

# renaming variables for convenience
names(init.data) = tolower(names(init.data))
names(init.data)[1] = "play"

# fixing rounding error for distance
for (i in 2:nrow(init.data)) {
  if (init.data$dn[i]==1 | is.na(init.data$dn[i])) { next }
  init.data$dist[i] = init.data$dist[i-1] - init.data$gn.ls[i-1]
}
```

```{r}
## Cleaning

# creating game ID
first.plays = which(init.data$play==2)
init.data$game = length(first.plays)
for (i in 1:(length(first.plays)-1)) {
  first = first.plays[i]
  last = first.plays[i+1]-1
  init.data$game[first:last] = i
}

# fixing yards to endzone
negative.yds = init.data$yard.ln < 0
na.yds = is.na(negative.yds)
negative.yds[na.yds] = FALSE
init.data[negative.yds, "yard.ln"] = init.data[negative.yds, "yard.ln"] + 100
names(init.data)[5] = "yds.to.endzone"

# creating drive ID
insert = data.frame(play = 11, odk = as.factor("O"), dn = 0, dist = -1, 
                    yds.to.endzone = 101, gn.ls = -101, result = as.factor(""), 
                    play.type = as.factor("Run"), game = 8)
init.data = rbind(init.data[1:1256, ], insert, init.data[1257:2082, ])

init.data$drive = rep(0, dim(init.data)[1])
prev.plays = 1

drive.preceders = c("KO", "KO Rec", "Onside Kick Rec")
drive.enders.play.type = c("Punt Rec", "Punt", "Extra Pt.", "Extra Pt. Block", 
                           "FG Block", "FG", "2 Pt.", "2 Pt. Defend")
drive.enders.result = c("Fumble", "Interception", "Sack, Fumble")

od = c(as.factor("O"), as.factor("D"))
num.games = max(init.data$game)

for (i in 1:num.games) { # Go through every game
  ind.game = init.data[init.data$game == i, ]
  num.plays = max(ind.game$play)
  drive.col = rep(0, num.plays)
  drive = 1
  
  for (j in 1:num.plays) { # Go through every play in the game
    cur.result = ind.game[j, "result"]
    cur.play.type = ind.game[j, "play.type"]
    
    if ((cur.play.type %in% drive.preceders) &&
        (j != 1) &&
        (j != num.plays) &&
       !(ind.game[j - 1, "play.type"] %in% drive.enders.play.type) &&
       !(ind.game[j - 1, "play.type"] %in% drive.preceders)) {
      drive = drive + 1
    }
    
    drive.col[j] = drive
    
    if ((j != 1) && # Not opening kickoff
        (j != num.plays) && # Don't want index out of bounds later
        
        # Fumbles, Interceptions, Punts, scoring plays
        ((cur.play.type %in% drive.enders.play.type) ||
         ((cur.result %in% drive.enders.result) &&
          (ind.game[j, "odk"] %in% od) && # Current play must be offense or defense
          (ind.game[j + 1, "odk"] %in% od) && # Next play must be offense or defense
          (ind.game[j, "odk"] != ind.game[j + 1, "odk"]))) ||
        
        # Turnover on downs
        ((ind.game[j, "odk"] %in% od) && # Current play must be offense or defense
         (ind.game[j + 1, "odk"] %in% od) && # Next play must be offense or defense
         (ind.game[j, "odk"] != ind.game[j + 1, "odk"])) # Consecutive plays are on different sides of the ball
        ) {
      drive = drive + 1
    }
  }
  
  init.data[prev.plays:(num.plays + prev.plays - 1), "drive"] = drive.col
  prev.plays = prev.plays + num.plays
}

init.data[init.data$play.type %in% drive.preceders, "drive"] = NA
```

```{r}
# creating drive outcome
last.plays = which(!mapply(identical, init.data$drive, lead(init.data$drive, default=0)) & 
                     !is.na(init.data$drive))
last.results = init.data$play.type[last.plays]
down = init.data$dn[last.plays]
result = init.data$result[last.plays]
last.results = ifelse((last.results=="Pass" | last.results=="Run") & down==4, "Turnover on Downs", 
               ifelse((last.results=="Pass" | last.results=="Run") & result %in% drive.enders.result,
                      "Turnover",
               ifelse(last.results=="Pass" | last.results=="Run", "Time Expired",
               ifelse(last.results=="Punt Rec", "Punt", 
               ifelse(last.results %in% c("Extra Pt.","Extra Pt. Block","2 Pt.","2 Pt. Defend"), "TD",
               ifelse(last.results=="FG Block", "FG", last.results))))))
offset = 0
init.data$drive.outcome = NA
for (i in 1:max(init.data$game)) {
  ind = which(init.data$game==i)
  init.data$drive.outcome[ind] = last.results[init.data$drive[ind] + offset]
  offset = offset + max(init.data$drive[ind], na.rm=TRUE)
}

# # creating next scoring play
# TD.score = c("Complete, TD", "Rush, TD", "Interception, Def TD", "Scramble, TD",
#              "Blocked, Def TD", "Fumble, Def TD") # check the result column
FG.score = c("FG", "FG Block") # check the play type column, and then result column for good
# safety.score = c("Safety")
# 
#   #Get indices for TDs
# TD.score.inds = which(init.data$result %in% TD.score)
# 
#   #Get indices for FGs

#Manually input missing FG good/no good values
FG.rows = init.data[init.data$play.type %in% FG.score, ]
FG.rows[c(5, 6, 9, 20, 21, 22), "result"] = "Good"
FG.rows[c(8, 23, 24, 25, 26, 28, 29), "result"] = "No Good"
  #Index 29 was a muffed FG attempt
init.data[init.data$play.type %in% FG.score, "result"] = FG.rows$result

# FG.na.rm.rows = FG.rows[!is.na(FG.rows$filled), ] # Removes incorrectly tagged FGs (really XPs)
# FG.good.rows = FG.na.rm.rows[FG.na.rm.rows$filled == "Good", ]
# FG.score.inds = rep(0, length(FG.good.rows$filled))
# for (i in 1:length(FG.good.rows$filled)) {
#   play = FG.good.rows[i, "play"]
#   game = FG.good.rows[i, "game"]
#   ind = which(init.data$game == game & init.data$play == play)
#   FG.score.inds[i] = ind
# }
# 
#   #Get indices for safeties
# safety.score.inds = which(init.data$result %in% safety.score)
# 
# if (length(safety.score.inds) == 0) {inds.merged = sort(append(TD.score.inds, FG.score.inds))
#  } else inds.merged = sort(append(TD.score.inds, FG.score.inds, safety.score.inds))

#Outline
  #TD Score
    #TD For (on O, or on D + int/fumble TD)
    #TD Against (on D, or on O +int/fumble TD)
  #FG Score
    #FG For (on O previous play + good, on FG unit)
    #FG Against (on D previous play + good, on FG Block unit)
  #Safety Score
    #Safety Score (on D)
    #Safety Against (on O)
  #No score
    #No other scores for rest of game

init.data$next.score = NA

init.data$TD.score = str_detect(init.data$result, "TD")
init.data[is.na(init.data$TD.score), "TD.score"] = F 
init.data$FG = str_detect(init.data$play.type, "FG")
init.data[is.na(init.data$FG), "FG"] = F 
init.data$FG.score = ((init.data$FG == T) & (init.data$result == "Good"))
init.data$safety.score = F # implement once we have data with safeties

init.data$sp = ifelse(init.data$TD.score + init.data$FG.score + init.data$safety.score >= 1, 
                      T,
                      F)

find.next.score.game = function(data) {
  
  # Which rows are the scoring plays:
  score.plays = which(data$sp)
  
  find.next.score = function(play.ind, score.plays.inds, data) {
    
    next.score.ind = score.plays.inds[which(score.plays.inds >= play.ind)[1]]
    
    if(is.na(next.score.ind)) {
      
      cat("\nThere is no score.")
      
      score.type = "No Score"
      
    } else {
      
      cur.odk = init.data[play.ind, "odk"] # CMU currently on offense or defense
      cur.result = init.data[play.ind, "result"] # Current play result
      cur.play.type = init.data[play.ind, "play.type"] # Current play type
      
      #TDs:
      if(data$TD.score[next.score.ind]) {
        
        score.type = ifelse((cur.odk == "O" | # offensive TD
                           ((cur.odk == "D") & # defensive TD
                           ((cur.result == "Interception, Def TD") | #caused by an int
                            (cur.result == "Fumble, Def TD")))), #caused by a fumble
                             "TD For",
                             "TD Against")
        
        cat("\nThe next score is a", score.type)

        #FGs
      } else if(data$FG.score[next.score.ind]) {
        
        score.type = ifelse(cur.play.type == "FG", 
                            "FG For", # FG unit on field
                            "FG Against") # FG block unit on field
        
        cat("\nThe next score is a", score.type)
        
        #Safeties
      } else if(data$safety.score[next.score.ind]) {
        
        score.type = "Safety" #Handle logic later
        
        #Error
      } else {
        
        score.type = NA
        
      }
    }
    
    return(data.frame(next.score = score.type))
    
  }
  
  res = lapply(1:nrow(data), find.next.score, 
               score.plays.inds = score.plays, data = init.data) %>% 
    bind_rows()
  
  print(res)
  
  return(res)
}

init.data$next.score = map_dfr(unique(init.data$game), 
        function(x) {
          init.data %>% 
            filter(game == x) %>% 
            find.next.score.game
        })

# for (game.ind in 1:num.games) {
#   if (game.ind > 1) break
#   ind.game = init.data[init.data$game == game.ind, ]
#   
#   
#   for (play.ind in 1:length(ind.game$play)) {
#     global.ind = which((init.data$game == i) & (init.data$play == play.ind))
#     next.score.ind = score.plays[which(score.plays >= play.ind)[1]]
#     
#     
# }


# for (i in 1:num.games) { # quite inefficient code :(
#   if (i > 1) break
#   
#   #cat("Game", i)
#   
#   ind.game = init.data[init.data$game == i, ]
#   ind.game = ind.game[!is.na(ind.game$drive.outcome), ]
#   
#   # TD.rows = ind.game[ind.game$drive.outcome == "TD", ]
#   # FG.rows = ind.game[ind.game$drive.outcome == "FG", ]
#   # safety.rows = ind.game[ind.game$drive.outcome == "Safety", ]
#   # no.score.rows = ind.game[ind.game$drive.outcome == "Time Expired", ]
#   
#   score.rows = ind.game[(ind.game$drive.outcome == "TD") | 
#                         (ind.game$drive.outcome == "FG") | 
#                         (ind.game$drive.outcome == "Safety") | 
#                         (ind.game$drive.outcome == "Time Expired"), ]
#   
#   for (score.ind in 1:(dim(score.rows)[1])) {
#     
#     # cat("\nRow:", j)
#     # cat("\nTheoretical Next play:", score.rows[score.ind, "play"] + 1)
#     # cat("\nActual Next Play:", score.rows[score.ind + 1, "play"])
#     
#     
#     if ((score.ind == (dim(score.rows)[1])) | 
#         (score.rows[score.ind, "play"] + 1 != score.rows[score.ind + 1, "play"])) {
#       # cat("\nEntered if statement.")
#       
#       global.ind = which((init.data$game == i) & 
#                          (init.data$play == score.rows[score.ind, "play"])) #index in init.data
#       prev.odk = init.data[global.ind - 1, "odk"]
#       prev.result = init.data[global.ind - 1, "result"]
#       cur.play.type = init.data[global.ind, "play.type"]
#       drive.outcome = score.rows[score.ind, "drive.outcome"]
#       
#       cat("\nDrive outcome:", drive.outcome)
#       
#       if (drive.outcome == "TD") {
#         cat("\nENTERED TD CASE")
#         cat("\nPrevious side of posession:", prev.odk)
#         cat("\nPrevious result:", prev.result)
#         
#         score.type = ifelse((prev.odk == "O" | # offensive TD
#                                ((prev.odk == "D") & # defensive TD
#                                   ((prev.result == "Interception, Def TD") | #caused by an int
#                                      (prev.result == "Fumble, Def TD")))), #caused by a fumble
#                             "TD For",
#                             "TD Against")
#         init.data[start.ind:global.ind, "next.score"] = score.type
#         start.ind = global.ind + 1
#       }
#       else if (drive.outcome == "FG") {
#         cat("\nENTERED FG CASE")
#         cat("\nCurrent play type:", cur.play.type)
#         
#         score.type = ifelse(cur.play.type == "FG",
#                             "FG For",
#                             "FG Against")
#         
#         cat("\nScore type:", score.type)
#         
#         init.data[start.ind:global.ind, "next.score"] = score.type
#         start.ind = global.ind + 1
#       }
#       else if (drive.outcome == "Safety") {
#         cat("\nENTERED SAFETY CASE")
#       }
#       else if (drive.outcome == "Time Expired") {
#         cat("\nENTERED NO SCORE CASE")
#         
#         init.data[start.ind:global.ind, "next.score"] = "No Score"
#         start.ind = global.ind + 1
#       }
#     }
#   }
# }
```

