---
title: "2022 PBP Scrape"
author: "Marion Haney"
date: '2023-03-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
require(purrr)
require(dplyr)
```

Make an empty data frame
```{r}
df = data.frame()
```


Get links for each game of the PAC season
```{r}
seasonLinks = getSeasonLinks(2022, 11)
teamData = getAllTeams()
pacTeams = getConferenceTeams(teamData, "PAC")
pac.teams.df = data.frame(pacTeams)
playByPlayLinks = c()
driveSummaryLinks = c()
for (wk in seasonLinks) {
  weekPBPLinks = getWeekPlayByPlayLinks(wk)
  weekDSLinks = getWeekDriveSummaryLinks(wk)
  playByPlayLinks = append(playByPlayLinks, weekPBPLinks)
  driveSummaryLinks = append(driveSummaryLinks, weekDSLinks)
}
```


Get team Play by Play for 2022 season weeks 1-11 (counting bye week)
```{r}
bigBadTable = NULL
team.df = data.frame(getPlayByPlayTable(playByPlayLinks, driveSummaryLinks, bigBadTable, wantedTeams = pacTeams))
```


Combine with df
```{r}
df = rbind(df, team.df)
# remove duplicate rows
df.unq = df %>% distinct() 
```

Save unique df
```{r}
write.csv(df.unq, "PAC-2022-pbp3.csv", row.names=FALSE)
```

