---
title: "Game Scraping Testing"
author: "Jordan Gilbert, Marion Haney"
date: "2023-02-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
```

```{r}
# url to all D3 games of particular year in particular week

url = "https://www.d3football.com/scoreboard/2022/composite?view=1"

# schedule of that week and year
schedule = read_html(url, as.data.frame = TRUE, stringsAsFactors = TRUE)
x = schedule %>% html_nodes("table") %>% .[[1]]

# schedule as table
fullSchedule = x %>% html_table(fill = TRUE)

# all links on table
allLinks = x %>% html_nodes("a") %>% html_attr("href") %>% grep("boxscores", ., value = TRUE)
```

```{r}
# links to play by play
pbp_links = unlist(lapply(allLinks, function(x) {begin = "https://www.d3football.com"; end = "?view=plays";
  adding = paste(begin, x, sep = ""); ending = paste(adding, end, sep = "");
  return(ending)}))

# links to drive summary
ds_links = unlist(lapply(allLinks, function(x) {begin = "https://www.d3football.com"; end = "?view=drives";
  adding = paste(begin, x, sep = ""); ending = paste(adding, end, sep = "");
  return(ending)}))
```

```{r}
## game series
#series = head(links, 1)
#
## play by play of game
#gameSeries = read_html(series, as.data.frame = TRUE, stringsAsFactors = TRUE)
#y = gameSeries %>% html_nodes("table") %>% .[[3]]
#
## play by play as table
#game = y %>% html_table(fill = TRUE)
#colnames(game) = c("Situation", "Play")
##print(game)
#
## getting teams, location, date, time
#setting = gameSeries %>% html_nodes("td") %>% .[[1]] %>% html_text()
#setting = unlist(str_extract_all(setting, "[^\n\r\t]"))
#setting = str_c(setting, collapse = "")
#setting = unlist(str_split(setting, "  "))
#teamsLocation = setting[2]
#teamsLocation = unlist(str_split(teamsLocation, " - "))
#teams = teamsLocation[1]
#teams = unlist(str_split(teams, " at "))
#awayTeam = trimws(teams[1], which = "left")
#homeTeam = teams[2]
#location = teamsLocation[2]
#dateTime = setting[3]
#dateTime = unlist(str_split(dateTime, " - "))
#date = dateTime[1]
#time = dateTime[2]
#
## getting abbreviations for the teams
#for (i in 3:5) {
#  startOfGame = game[i,]
#  if (!(is.na(str_extract(startOfGame$Play, "ball")))) {
#      awayAbb = gsub(".*at (.+)", "\\1", startOfGame$Situation)
#      awayAbb = unlist(str_extract_all(awayAbb, "[[:alpha:]]"))
#      awayAbb = str_c(awayAbb, collapse = "")
#      homeAbb = gsub(".*on (.+),.*", "\\1", startOfGame$Play)
#      homeAbb = unlist(str_extract_all(homeAbb, "[[:alpha:]]"))
#      homeAbb = str_c(homeAbb, collapse = "")
#      break
#    }
#}
```

```{r}
gamePlayByPlay = function(game, date, time, location, homeTeam, homeAbb, awayTeam, awayAbb) {
  downs = c("1", "2", "3", "4", "OT")
  quarter = list()
  possession = list()
  down = list()
  distancetoGo = list()
  distancetoGoal = list()
  playType = list()
  netYards = list()
  scoreHome = list()
  scoreAway = list()
  Outcome = list()
  numDrives = list()
  totalPlays = list()
  binaryPointsScored = list()
  binaryCompletedPass = list()
  binaryIncompletePass = list()
  binaryRun = list()
  binaryTouchdown = list()
  binaryFieldGoal = list()
  binaryPenalty = list()
  binaryPunt = list()
  binarySack = list()
  binaryInterception = list()
  binarySafety = list()
  binaryFumble = list()
  binaryExtraPoint = list()
  binaryTurnover = list()
  currentQuarter = NULL
  lastPossession = "NULL"
  currentPossession = NULL
  driveNumberAway = 0
  driveNumberHome = 0
  driveNumber = 0
  numberOfPlaysAway = 0
  numberOfPlaysHome = 0
  numPlays = 0
  playDescription = list()
  
  # current possession defaulted to home team
  currentPossession = homeTeam
  
  validPlays = "(rush|pass|Pass|PENALTY|fumble|sacked|punt|field goal|kick|Kneel|caught|Penalty|blocked)"
  
  for (i in 1:nrow(game)) {
    # Binary Outcomes
    is.pointsScored = FALSE
    is.completedPass = FALSE
    is.incompletePass = FALSE
    is.run = FALSE
    is.touchdown = FALSE
    is.fieldGoal = FALSE
    is.penalty = FALSE
    is.punt = FALSE
    is.sack = FALSE
    is.intercepted = FALSE
    is.safety = FALSE
    is.fumble = FALSE
    is.extraPoint = FALSE
    is.turnover = FALSE
    
    # Information about Game
    situation = game$Situation[i]
    if (situation == "") {
      situation = game$Situation[i-1]
    }
    play = game$Play[i]
    startsWith = substr(situation, 1, 1)
    
    # Gets Quarter of the Game
    if (nchar(situation) <= 3 && startsWith %in% downs) {
      currentQuarter = situation
      # no other information, so skip
      next
    }
    
    # Gets Possession at Time
    if (str_detect(situation, "[0-1][0-9]:[0-5][0-9]") & !str_detect(situation, "elapsed")) {
      currentPossession = sub(" at.*", "", situation)
      # update drive number and possession
      if (lastPossession != currentPossession) {
        if (currentPossession == homeTeam) {
          driveNumberHome = driveNumberHome + 1
          driveNumber = driveNumberHome
        }
        else {
          driveNumberAway = driveNumberAway + 1
          driveNumber = driveNumberAway
        }
        lastPossession = currentPossession
      }
      # no other information, so skip
      next
    }
    
    # Looks at columns with plays only
    if (!(grepl("[1-4][(st)|(nd)|(rd)|(th)]", substr(situation, 1, 3)))) {
      # has no wanted information, so skip
      next
    }
    if (situation == play) {
      # has no wanted information, so skip
      next
    }
    
    # If just update on score, skip
    if (grepl("([[:alpha:]]|[[:punct:]]|[[:space:]])+ [[:digit:]]+, ([[:alpha:]]|[[:punct:]]|[[:space:]])+ [[:digit:]]", play)) {
      # has no wanted information, so skip
      next
    }
    
    # if recap of field position, skip
    if (grepl("[1-4][[:alpha:]]{2} and [[:digit:]]+.", play)) {
      # has no wanted information, so skip
      next
    }
    
    # if not valid play, skip
    if (nchar(play) <= 1) {
      # has no wanted information, so skip
      next
    }
    
    # if play is time update, skip
    if (str_detect(play, "[0-1]*[0-9]:[0-5][0-9]") & is.na(str_extract(play, validPlays))) {
      # has no wanted information, so skip
      next
    }
    
    # Plays with information
    if (nchar(situation) >= 25 && startsWith %in% downs) {
      
      # down
      currentDown = startsWith
      # distance to first down
      currentDistanceToGo = gsub(".*and (.+) at.*", "\\1", situation)
      
      #if (!(is.na(str_extract(play,
      #            "(kickoff|hurry|ball|drive|quarter|half|Timeout|game|toss|Toss|QB|receive|defers|defend|clock|Clock|ejected|snap|timing|pylon|pattern|wide left|broken up|conduct|DOWN|illegal)")))) {
        # has no wanted information, so skip
      #  next
      #}
      if ((is.na(str_extract(play, validPlays)) | (!is.na(str_extract(play, "(kickoff|ball|drive|quarter|half|Timeout|toss|Toss|ejected|pylon|illegal|conduct|receive)"))))) 
        {
        # has no wanted information, so skip
        next
      }
      
      # abbreviation of location on field
      abb = gsub(".*at (.+)", "\\1", situation)
      lets = unlist(str_extract_all(abb, "[[:alpha:]]"))
      toGoal = (unlist(str_extract_all(abb, "[[:digit:]]")))
      abb = str_c(lets, collapse = "")
      toGoal = as.numeric(str_c(toGoal, collapse = ""))
      # get distance from goal
      if (currentPossession == homeTeam | 
          str_detect(str_to_lower(currentPossession), str_to_lower(homeTeam)) | 
          str_detect(str_to_lower(homeTeam), str_to_lower(currentPossession))) {
        if (abb == homeAbb) {
          currentDistanceToGoal = as.character(100 - toGoal)
        }
        else {
          currentDistanceToGoal = as.character(toGoal)
        }
      }
      else {
      #else if (currentPossession == awayTeam | str_detect(str_to_lower(currentPossession), str_to_lower(awayTeam))) {
        if (abb == awayAbb) {
          currentDistanceToGoal = as.character(100 - toGoal)
        }
        else {
          currentDistanceToGoal = as.character(toGoal)
        }
      }
      
      # get play
      currentPlay = str_extract(play, "(rush|pass|Pass|PENALTY|fumble|sacked|punt|field goal|kick|Kneel|caught|Penalty|blocked)")
      if (is.na(currentPlay)) {print(play); print(game$Play[i-1])}
      if (str_detect(play, "PENALTY") | str_detect(play, "Penalty")) {
        yards = "Penalty"
        is.penalty = TRUE
      }
      else if (currentPlay == "kick") {
        yards = "Extra Point Attempt"
      }
      else if (currentPlay == "rush") {
        if (!(is.na(str_extract(play, "(no gain|failed)")))) {
          yards = "0"
        }
        else {
          yards = sub(".*for (.+) yard(s?)(.*?) .*", "\\1", play)
          if (!(is.na(str_extract(play, "loss")))) {
            if (!(is.na(str_extract(yards, "loss")))) {
              yards = str_extract(yards, "[:digit:]+")
            }
            yards = as.character(as.numeric(yards) * -1)
          }
        }
        is.run = TRUE
      }
      else if (currentPlay == "pass" | currentPlay == "Pass" | currentPlay == "caught") {
        if (!(is.na(str_extract(play, "(incomplete|no gain)")))) {
          yards = "0"
          is.incompletePass = TRUE
        }
        else if (!(is.na(str_extract(play, "intercepted")))) {
          yards = "Intercepted"
          is.incompletePass = TRUE
          is.intercepted = TRUE
          is.turnover = TRUE
        }
        else {
          yards = sub(".*for (.+) yard(s?)(.*?) .*", "\\1", play)
          if (!(is.na(str_extract(play, "loss")))) {
            if (!(is.na(str_extract(yards, "loss")))) {
              yards = str_extract(yards, "[:digit:]+")
            }
            yards = as.character(as.numeric(yards) * -1)
          }
          is.completedPass = TRUE
        }
        
      }
      
      else if (currentPlay == "Kneel") {
        if (!(is.na(str_extract(play, "no gain")))) {
         yards = "0"
        }
        else {
          yards = sub(".*for (.+) yard(s?)(.*?) .*", "\\1", play)
          if (!(is.na(str_extract(play, "loss")))) {
            if (!(is.na(str_extract(yards, "loss")))) {
              yards = str_extract(yards, "[:digit:]+")
            }
            yards = as.character(as.numeric(yards) * -1)
          }
        }
      }
      
      else if (currentPlay == "punt") {
        yards = "Punt"
        is.punt = TRUE
      }
      else if (currentPlay == "field goal") {
        yards = "Field Goal"
        is.fieldGoal = TRUE
      }
      else if (currentPlay == "sacked") {
        yards = sub(".*for (.+) yard(s?)(.*?) .*", "\\1", play)
        if (!(is.na(str_extract(play, "loss")))) {
          if (!(is.na(str_extract(yards, "loss")))) {
            yards = str_extract(yards, "[:digit:]+")
          }
          yards = as.character(as.numeric(yards) * -1)
        }
        is.sack = TRUE
      }
      
      # get outcome
      play = tolower(play)
      touch = !(is.na(str_extract(play, "(touchdown|penalty|fumble|sacked|punt|incomplete|field goal|intercepted|kick|safety|block)")))
      if (touch) {
        touch = str_extract_all(play, "(touchdown|penalty|fumble|sacked|punt|incomplete|field goal|intercepted|kick|safety|block)")
        if (touch == "touchdown") {
          outcome = "Touchdown"
          is.touchdown = TRUE
          is.pointsScored = TRUE
        }
        else if (touch == "penalty") {
          outcome = "Penalty"
          is.penalty = TRUE
        }
        else if (touch == "fumble" | touch == "block") {
          outcome = "Fumble"
          is.fumble = TRUE
          recovery = sub(".* (?:recovered|returned) by (.+) at .*", "\\1", play)
          recoveredBy = sub("(.+) .+", "\\1", recovery)
          if ((recoveredBy != currentPossession & currentPossession != homeTeam) |
              (tolower(recoveredBy) != tolower(currentPossession) & currentPossession != homeTeam) |
              (recoveredBy == homeAbb & currentPossession != homeTeam) |
              (toupper(recoveredBy) == homeAbb & currentPossession != homeTeam)) {
            currentPossession = homeTeam
            is.turnover = TRUE
          } 
          else if ((recoveredBy != currentPossession & currentPossession != awayTeam) |
              (tolower(recoveredBy) != tolower(currentPossession) & currentPossession != awayTeam) |
              (recoveredBy == awayAbb & currentPossession != awayTeam) |
              (toupper(recoveredBy) == awayAbb & currentPossession != awayTeam)) {
            currentPossession = awayTeam
            is.turnover = TRUE
          }
        }
        else if (touch == "sacked") {
          outcome = "Sack"
          is.sack = TRUE
        }
        else if (touch == "punt") {
          outcome = "Punt"
          is.punt = TRUE
        }
        else if (touch == "incomplete") {
          outcome = "Incomplete Pass"
          is.incompletePass = TRUE
        }
        else if (touch == "field goal") {
          if (!(is.na(str_extract(play, "(missed|failed)")))) {
            outcome = "Missed Field Goal"         
          }
          else {
            outcome = "Field Goal"
            is.pointsScored = TRUE
          }
          is.fieldGoal = TRUE
        }
        else if (touch == "intercepted") {
          outcome = "Interception"
          is.intercepted = TRUE
          is.turnover = TRUE
        }
        else if (touch == "kick") {
          if (!(is.na(str_extract(play, "(missed|failed)")))) {
            outcome = "Missed Extra Point Attempt"
          }
          else {
            outcome = "Made Extra Point Attempt"
            is.pointsScored = TRUE
          }
          is.extraPoint = TRUE
        }
        else if (touch == "safety") {
          outcome = "Safety"
          is.safety = TRUE
          is.pointsScored = TRUE
        }
        else {
          outcome = str_to_lower(paste(unlist(touch), collapse = ", "))
          if (str_detect(outcome, "touchdown")) {
            is.touchdown = TRUE
            is.pointsScored = TRUE
          }
          if (str_detect(outcome, "fumble") | str_detect(outcome, "block")) {
            is.fumble = TRUE
            recovery = sub(".* (?:recovered|returned) by (.+) at .*", "\\1", play)
            recoveredBy = sub("(.+) .+", "\\1", recovery)
            recoveredBy = str_to_upper(recoveredBy)
            if ((recoveredBy == currentPossession & currentPossession != homeTeam) |
                (tolower(recoveredBy) == tolower(currentPossession) & currentPossession != homeTeam) |
                (recoveredBy == homeAbb & currentPossession != homeTeam) |
                (toupper(recoveredBy) == homeAbb & currentPossession != homeTeam)) {
              currentPossession = homeTeam
              is.turnover = TRUE
            } 
            else if ((recoveredBy == currentPossession & currentPossession != awayTeam) |
                (tolower(recoveredBy) == tolower(currentPossession) & currentPossession != awayTeam) |
                (recoveredBy == awayAbb & currentPossession != awayTeam) |
                (toupper(recoveredBy) == awayAbb & currentPossession != awayTeam)) {
              currentPossession = awayTeam
              is.turnover = TRUE
            }
          }
          if (str_detect(outcome, "sacked")) {
            is.sack = TRUE
          }
          if (str_detect(outcome, "punt")) {
            is.punt = TRUE
          }
          if (str_detect(outcome, "penalty")) {
            is.penalty = TRUE
          }
          if (str_detect(outcome, "safety")) {
            is.safety = TRUE
            is.pointsScored = TRUE
          }
          if (str_detect(outcome, "kick")) {
            is.extraPoint = TRUE
            if (str_detect(play, "attempt good")) {
              is.pointsScored = TRUE
            }
          }
        }
      }
      else {
        outcome = ""
      }
      
      # total number of plays
      if (currentPossession == homeTeam) {
        if (!(currentPlay == "PENALTY" | str_detect(play, "NO PLAY"))) {
          numberOfPlaysHome = numberOfPlaysHome + 1
          numPlays = numberOfPlaysHome
        }
      }
      else {
        if (!(currentPlay == "PENALTY" | str_detect(play, "NO PLAY"))) {
          numberOfPlaysAway = numberOfPlaysAway + 1
          numPlays = numberOfPlaysAway
        }
      }
    }
    
    quarter = c(quarter, list(currentQuarter))
    possession = c(possession, list(currentPossession))
    down = c(down, list(currentDown))
    distancetoGo = c(distancetoGo, list(currentDistanceToGo))
    playType = c(playType, list(currentPlay))
    netYards = c(netYards, list(yards))
    Outcome = c(Outcome, list(outcome))
    distancetoGoal = c(distancetoGoal, list(currentDistanceToGoal))
    numDrives = c(numDrives, list(driveNumber))
    totalPlays = c(totalPlays, list(numPlays))
    binaryPointsScored = c(binaryPointsScored, list(is.pointsScored))
    binaryCompletedPass = c(binaryCompletedPass, list(is.completedPass))
    binaryIncompletePass = c(binaryIncompletePass, list(is.incompletePass))
    binaryRun = c(binaryRun, list(is.run))
    binaryTouchdown = c(binaryTouchdown, list(is.touchdown))
    binaryFieldGoal = c(binaryFieldGoal, list(is.fieldGoal))
    binaryPenalty = c(binaryPenalty, list(is.penalty))
    binaryPunt = c(binaryPunt, list(is.punt))
    binarySack = c(binarySack, list(is.sack))
    binaryInterception = c(binaryInterception, list(is.intercepted))
    binarySafety = c(binarySafety, list(is.safety))
    binaryFumble = c(binaryFumble, list(is.fumble))
    binaryExtraPoint = c(binaryExtraPoint, list(is.extraPoint))
    binaryTurnover = c(binaryTurnover, list(is.turnover))
    playDescription = c(playDescription, list(play))
    
  }
  
  PlaybyPlayTable = data.frame(Date = date, Time = time, Location = location, "Home Team" = homeTeam, "Home Team Abbreviation" = homeAbb, "Away Team" = awayTeam, "Away Team Abbreviation" = awayAbb, Quarter = unlist(quarter), "Team Possession" = unlist(possession), Down = unlist(down), "Distance to First Down" = unlist(distancetoGo), "Distance to Touchdown" = unlist(distancetoGoal), "Play Type" = unlist(playType), "Yards" = unlist(netYards), Outcome = unlist(Outcome), "Points Scored?" = unlist(binaryPointsScored), "Completed Pass?" = unlist(binaryCompletedPass), "Incomplete Pass?" = unlist(binaryIncompletePass), "Run?" = unlist(binaryRun), "Touchdown?" = unlist(binaryTouchdown), "Field Goal?" = unlist(binaryFieldGoal), "Penalty?" = unlist(binaryPenalty), "Punt?" = unlist(binaryPunt), "Sack?" = unlist(binaryPunt), "Interception?" = unlist(binaryInterception), "Safety?" = unlist(binarySafety), "Fumble?" = unlist(binaryFumble), "Extra Point?" = unlist(binaryExtraPoint), "Turnover?" = unlist(binaryTurnover), "Drive Number" = unlist(numDrives), "Team Play Number" = unlist(totalPlays), "Play Description" = unlist(playDescription))
  
  return(PlaybyPlayTable)
}
```

```{r}
mapAbbreviations = function(homeTeam, awayTeam, Abb1, Abb2, currTeam, currAbb, opponentSide = TRUE) {
  # home team, scored from opponent's side
  if ((currTeam == homeTeam | str_detect(tolower(currTeam), tolower(homeTeam)) | 
       str_detect(tolower(homeTeam), tolower(currTeam))) & opponentSide) {
    if (currAbb == Abb1) {
      homeAbb = Abb2
      awayAbb = Abb1
    }
    else {
      homeAbb = Abb1
      awayAbb = Abb2
    }
  }
  # home team, scored from own side
  else if ((currTeam == homeTeam | str_detect(tolower(currTeam), tolower(homeTeam)) | 
       str_detect(tolower(homeTeam), tolower(currTeam))) & !opponentSide) {
    if (currAbb == Abb1) {
      homeAbb = Abb1
      awayAbb = Abb2
    }
    else {
      homeAbb = Abb2
      awayAbb = Abb1
    }
  }
  # away team, scored from opponent's side
  else if ((currTeam == awayTeam | str_detect(tolower(currTeam), tolower(awayTeam)) | 
       str_detect(tolower(awayTeam), tolower(currTeam))) & opponentSide) {
    if (currAbb == Abb1) {
      homeAbb = Abb1
      awayAbb = Abb2
    }
    else {
      homeAbb = Abb2
      awayAbb = Abb1
    }
  }
  # away team, scored from own side
  else if ((currTeam == awayTeam | str_detect(tolower(currTeam), tolower(awayTeam)) | 
       str_detect(tolower(awayTeam), tolower(currTeam))) & !opponentSide) {
    if (currAbb == Abb1) {
      homeAbb = Abb2
      awayAbb = Abb1
    }
    else {
      homeAbb = Abb1
      awayAbb = Abb2
    }
  }
  return(c(homeAbb = homeAbb, awayAbb = awayAbb))
}
```

```{r}
findNearestDriveStart = function(drive_start_idx, scoring_play_idx) {
  drive_idx = 1
  scoring_idx = 1
  result = rep(0, length(scoring_play_idx) - 1)
  while (scoring_idx < length(scoring_play_idx) - 1) {
    if (drive_start_idx[drive_idx] < scoring_play_idx[scoring_idx]) {
      result[scoring_idx] = drive_idx
      drive_idx = drive_idx + 1
    }
    else {
      scoring_idx = scoring_idx + 1
    }
  }
  return(drive_start_idx[result])
}
```

```{r}
bigBadTable = NULL
for (i in 1:length(pbp_links)) {
  
  # ----------------- Extract Data in table format ----------------------------
  
  # play by play of game
  gameSeries = read_html(pbp_links[i], as.data.frame = TRUE, stringsAsFactors = TRUE)
  pbp = gameSeries %>% html_nodes("table") %>% .[[3]]
  # play by play as table
  game = pbp %>% html_table(fill = TRUE)
  colnames(game) = c("Situation", "Play")
  #print(game)
  
  # drive summary of game
  gameSummary = read_html(ds_links[i], as.data.frame = TRUE, stringsAsFactors = TRUE)
  ds = gameSummary %>% html_nodes("table") %>% .[[3]]
  # drive summary as table
  drive_sum = ds %>% html_table(fill = TRUE)
  colnames(drive_sum) = c("Team", "QTR", "Start", "Poss.", "Began", "Plays", "Yards", "Result")
  #print(drive_sum)
  
  # ------------------- Gather Information ------------------------------------
  
  # getting teams, location, date, time
  setting = gameSeries %>% html_nodes("td") %>% .[[1]] %>% html_text()
  setting = unlist(str_extract_all(setting, "[^\n\r\t]"))
  setting = str_c(setting, collapse = "")
  setting = unlist(str_split(setting, "  "))
  teamsLocation = setting[2]
  teamsLocation = unlist(str_split(teamsLocation, " - "))
  teams = teamsLocation[1]
  teams = unlist(str_split(teams, " at "))
  awayTeam = trimws(teams[1], which = "left")
  homeTeam = teams[2]
  location = teamsLocation[2]
  dateTime = setting[3]
  dateTime = unlist(str_split(dateTime, " - "))
  date = dateTime[1]
  time = dateTime[2]
  
  # getting abbreviations for the teams
  awayAbb = gsub(".*at (.+)", "\\1", game[3, ]$Situation)
  awayAbb = unlist(str_extract_all(awayAbb, "[[:alpha:]]"))
  awayAbb = str_c(awayAbb, collapse = "")
  homeAbbFound = FALSE
  index = 4
  while (!homeAbbFound) {
    startOfGame = game[index,]
    if (grepl("[1-4][(st)|(nd)|(rd)|(th)]", substr(startOfGame$Situation, 1, 3))) {
      homeAbb = gsub(".*at (.+)", "\\1", startOfGame$Situation)
      homeAbb = unlist(str_extract_all(homeAbb, "[[:alpha:]]"))
      homeAbb = str_c(homeAbb, collapse = "")
      if (homeAbb != awayAbb) {
        homeAbbFound = TRUE
      }
    }
    index = index + 1
  }
  
  # Verify home and away abbreviations are correct by finding a scoring play under 50 yards and seeing if abbreviations match up
  Abb1 = awayAbb
  Abb2 = homeAbb
  
  
  scoringPlays = c("TD", "FG", "SAF")
  scoringDrives = subset(drive_sum, Result %in% scoringPlays)
  scoringPBP = subset(game, str_detect(tolower(Play), "touchdown|field goal|safety"))
  
  pbpscoringplays = intersect(which(str_detect(tolower(game$Play), "touchdown|field goal|safety")),
                          which(!str_detect(tolower(game$Play), "interception|fumble|intercepted|fumbled")))
  
  pbppossesplays = which(str_detect(game$Situation, "[0-1][0-9]:[0-5][0-9]") & !str_detect(game$Situation, "elapsed") & game$Situation == game$Play) + 1
  
  starts = findNearestDriveStart(pbppossesplays, pbpscoringplays)
  
  scoringAbbFound = FALSE
  
  for (j in 1:nrow(scoringDrives)) {
    drive = scoringDrives[j, ]
    # check same input on drive summary and pbp
    pbp_found_abb = gsub(".*at (.+)", "\\1", game[starts[j], ]$Situation)
    pbp_found_abb = str_trim(pbp_found_abb, "both")
    #pbp_found_abb = unlist(str_extract_all(pbp_found_abb, "[[:alpha:]]"))
    #pbp_found_abb = str_c(pbp_found_abb, collapse = "")
    
    if (!is.na(pbp_found_abb) & drive$Began != pbp_found_abb) {
      next
    }
    
    foundAbb = unlist(str_extract_all(drive$Began, "[[:alpha:]]"))
    foundAbb = str_c(foundAbb, collapse = "")
    # Touchdown
    if (drive$Result == "TD") {
      if (drive$Yards < 50) {
        abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = TRUE)
        homeAbb = abbs["homeAbb"]
        awayAbb = abbs["awayAbb"]
        scoringAbbFound = TRUE
      }
      else if (drive$Yards > 50) {
        abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = FALSE)
        homeAbb = abbs["homeAbb"]
        awayAbb = abbs["awayAbb"]
        scoringAbbFound = TRUE
      }
    }
    # Field Goal
    else if (drive$Result == "FG") {
      if (drive$Yards > 50) {
        abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = FALSE)
        homeAbb = abbs["homeAbb"]
        awayAbb = abbs["awayAbb"]
        scoringAbbFound = TRUE
      }
      else {
        foundAbbEnding = gsub(".*at (.+)", "\\1", game[pbpscoringplays[j], ]$Situation)
        foundAbbEnding = str_trim(foundAbbEnding, "both")
        foundAbbEnding = unlist(str_extract_all(foundAbbEnding, "[[:alpha:]]"))
        foundAbbEnding = str_c(foundAbbEnding, collapse = "")
        print(foundAbbEnding)
        if (foundAbb == foundAbbEnding) {
          abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = TRUE)
          homeAbb = abbs["homeAbb"]
          awayAbb = abbs["awayAbb"]
          scoringAbbFound = TRUE
        }
        else if (foundAbb != foundAbbEnding) {
          abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = FALSE)
          homeAbb = abbs["homeAbb"]
          awayAbb = abbs["awayAbb"]
          scoringAbbFound = TRUE
        }
      }
    }
    # Safety
    else if (drive$Result == "SAF") {
      if (drive$Yards > -50) {
        abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = FALSE)
        homeAbb = abbs["homeAbb"]
        awayAbb = abbs["awayAbb"]
        scoringAbbFound = TRUE
      }
      else if (drive$Yards < -50) {
        abbs = mapAbbreviations(homeTeam, awayTeam, Abb1, Abb2, drive$Team, foundAbb, opponentSide = TRUE)
        homeAbb = abbs["homeAbb"]
        awayAbb = abbs["awayAbb"]
        scoringAbbFound = TRUE
      }
    }
    
    # Found Abbreviations, break out of loop
    if (scoringAbbFound) {
      break
    }
  }
  
  # ------------------- Call Play by Play Function -----------------------------
  
  playByPlay = gamePlayByPlay(game, date, time, location, homeTeam, homeAbb, awayTeam, awayAbb)
  if (is.null(bigBadTable)) {
    bigBadTable = playByPlay
  }
  else {
    bigBadTable = rbind(bigBadTable, playByPlay)
  }
}
```



```{r}
bigBadTable = NULL
for (series in pbp_links) {
  # play by play of game
  gameSeries = read_html(series, as.data.frame = TRUE, stringsAsFactors = TRUE)
  y = gameSeries %>% html_nodes("table") %>% .[[3]]
  
  # play by play as table
  game = y %>% html_table(fill = TRUE)
  colnames(game) = c("Situation", "Play")
  #print(game)
  
  # getting teams, location, date, time
  setting = gameSeries %>% html_nodes("td") %>% .[[1]] %>% html_text()
  setting = unlist(str_extract_all(setting, "[^\n\r\t]"))
  setting = str_c(setting, collapse = "")
  setting = unlist(str_split(setting, "  "))
  teamsLocation = setting[2]
  teamsLocation = unlist(str_split(teamsLocation, " - "))
  teams = teamsLocation[1]
  teams = unlist(str_split(teams, " at "))
  awayTeam = trimws(teams[1], which = "left")
  homeTeam = teams[2]
  location = teamsLocation[2]
  dateTime = setting[3]
  dateTime = unlist(str_split(dateTime, " - "))
  date = dateTime[1]
  time = dateTime[2]
  
  # getting abbreviations for the teams
  awayAbb = gsub(".*at (.+)", "\\1", game[3, ]$Situation)
  awayAbb = unlist(str_extract_all(awayAbb, "[[:alpha:]]"))
  awayAbb = str_c(awayAbb, collapse = "")
  homeAbbFound = FALSE
  index = 4
  while (!homeAbbFound) {
    startOfGame = game[index,]
    if (grepl("[1-4][(st)|(nd)|(rd)|(th)]", substr(startOfGame$Situation, 1, 3))) {
      homeAbb = gsub(".*at (.+)", "\\1", startOfGame$Situation)
      homeAbb = unlist(str_extract_all(homeAbb, "[[:alpha:]]"))
      homeAbb = str_c(homeAbb, collapse = "")
      if (homeAbb != awayAbb) {
        homeAbbFound = TRUE
      }
    }
    index = index + 1
  }
  
  # Verify home and away abbreviations are correct by finding a scoring play under 50 yards and seeing if abbreviations match up
  Abb1 = awayAbb
  Abb2 = homeAbb
  scoringAbbFound = FALSE
  index = 4
  while (!scoringAbbFound) {
    startOfGame = game[index, ]
    situation = startOfGame$Situation
    play = startOfGame$Play
    play = tolower(play)
    foundAbb = NULL
    opponentSide = FALSE
    ownSide = FALSE
    
    scoringPlays = "(touchdown|field goal)"
    
    # "(rush|pass|Pass|PENALTY|fumble|sacked|punt|field goal|kick|Kneel|caught|Penalty|blocked)")
    if (!is.na(play) &
        str_detect(play, scoringPlays)) {
      
      # Field Goal
      if (str_detect(play, "field goal")) {
        foundAbb = gsub(".*at (.+)", "\\1", situation)
        foundAbb = unlist(str_extract_all(foundAbb, "[[:alpha:]]"))
        foundAbb = str_c(foundAbb, collapse = "")
        opponentSide = TRUE
      }
      
      # Offense Scoring
      else if (str_detect(play, "rush|pass") & !str_detect(play, "safety|fumble|interception")) {
        yards = sub(".*for (.+) yard(s?)(.*?) .*", "\\1", play)
        if (!(is.na(str_extract(play, "loss")))) {
          if (!(is.na(str_extract(yards, "loss")))) {
            yards = str_extract(yards, "[:digit:]+")
          }
          yards = as.character(as.numeric(yards) * -1)
        }
        foundAbb = gsub(".*at (.+)", "\\1", situation)
        foundAbb = unlist(str_extract_all(foundAbb, "[[:alpha:]]"))
        foundAbb = str_c(foundAbb, collapse = "")
        if (yards < 50) {
          opponentSide = TRUE
        }
        else {
          ownSide = TRUE
        }
      }
      
      # Defense Scoring
      else {
        next
        yards = sub(".*for (.+) yard(s?)(.*?) .*", "\\1", play)
        if (!(is.na(str_extract(play, "loss")))) {
          if (!(is.na(str_extract(yards, "loss")))) {
            yards = str_extract(yards, "[:digit:]+")
          }
          yards = as.character(as.numeric(yards) * -1)
        }  
        foundAbb = gsub(".*at (.+)", "\\1", situation)
        foundAbb = unlist(str_extract_all(foundAbb, "[[:alpha:]]"))
        foundAbb = str_c(foundAbb, collapse = "")
        
        if (yards < 50) {
        
        }
      }
      if (!is.null(foundAbb)) {
        while (!str_detect(situation, "[0-1][0-9]:[0-5][0-9]") & !situation == play ) {
          index = index - 1
          situation = game[index, ]$Situation
        }
        currentPossession = sub(" at.*", "", situation)
        # home team, scored from opponent's side
        if (currentPossession == homeTeam & opponentSide) {
          if (foundAbb == Abb1) {
            homeAbb = Abb2
            awayAbb = Abb1
          }
          else {
            homeAbb = Abb1
            awayAbb = Abb2
          }
        }
        # home team, scored from own side
        else if (currentPossession == homeTeam & ownSide) {
          if (foundAbb == Abb1) {
            homeAbb = Abb1
            awayAbb = Abb2
          }
          else {
            homeAbb = Abb2
            awayAbb = Abb1
          }
        }
        # away team, scored from opponent's side
        else if(currentPossession == awayTeam & opponentSide) {
          if (foundAbb == Abb1) {
            homeAbb = Abb1
            awayAbb = Abb2
          }
          else {
            homeAbb = Abb2
            awayAbb = Abb1
          }
        }
        # away team, scored from own side
        else if (currentPossession == awayTeam & ownSide) {
          if (foundAbb == Abb1) {
            homeAbb = Abb2
            awayAbb = Abb1
          }
          else{
            homeAbb = Abb1
            awayAbb = Abb2
          }
        }
        scoringAbbFound = TRUE
      }
      
    }
    index = index + 1
  }
  
  # # getting abbreviations for the teams
  # for (i in 3:5) {
  #   startOfGame = game[i,]
  #   if (!(is.na(str_extract(startOfGame$Play, "ball on")))) {
  #       awayAbb = gsub(".*at (.+)", "\\1", startOfGame$Situation)
  #       awayAbb = unlist(str_extract_all(awayAbb, "[[:alpha:]]"))
  #       awayAbb = str_c(awayAbb, collapse = "")
  #       homeAbb = gsub(".*on (.+)([[:punct:]])(.*)", "\\1", startOfGame$Play)
  #       homeAbb = gsub("[[:punct:]].*", "\\1", homeAbb)
  #       homeAbb = unlist(str_extract_all(homeAbb, "[[:alpha:]]"))
  #       homeAbb = str_c(homeAbb, collapse = "")
  #       break
  #     }
  # }
  
  playByPlay = gamePlayByPlay(game, date, time, location, homeTeam, homeAbb, awayTeam, awayAbb)
  if (is.null(bigBadTable)) {
    bigBadTable = playByPlay
  }
  else {
    bigBadTable = rbind(bigBadTable, playByPlay)
  }
}
```

