---
title: "getAllTeams"
author: "Jordan Gilbert, Marion Haney"
date: '2023-02-15'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
require(rje)
require(dplyr)
```


getAllTeams:
INPUT:
OUTPUT: a data frame containing strings of all the D3 football team names,
their nickname, location, conference, region, surface, and enrollment
DEFAULT: 

```{r}
getAllTeams = function() {
  tryCatch(
    {
      # all teams
      allTeams = "https://www.d3football.com/teams/index"
    
      # read table of teams, extract table, and fill table as data frame
      teams = read_html(allTeams, as.data.frame = TRUE, stringsAsFactors = TRUE)
      teams = teams %>% html_nodes("table") %>% .[[1]]
      teams = teams %>% html_table(fill = TRUE)
      return(teams)
    },
    error=function(e) {
      message('An Error Occurred')
      print(e)
      return(NA)
    },
    warning=function(w) {
      message('A Warning Occurred')
      print(w)
      return(NA)
    }
  )
}
```

Testing
```{r}
print(getAllTeams())
```



