---
title: "getConferenceTeams"
author: "Jordan Gilbert, Marion Haney"
date: '2023-02-15'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
require(rje)
require(dplyr)
require(assertthat)
```

getConferenceTeams:
INPUT: 
teamData: the output of getAllTeams
conference: the string of the conference
OUTPUT: vector containing the string names of all the D3 football teams
in the specified conference
DEFAULT: conference = "PAC"

```{r}
getConferenceTeams = function(teamData, conference = "PAC") {
  tryCatch(
    {
      validConfs = sort(unique(teamData$Conference))
      
      # check if string input
      if (!(is.string(conference))) {
        message("Invalid Conference Input")
        message("Valid Conference Input includes ...")
        return(validConfs)
      }
      conference = toupper(conference)
      
      # check if conference input in valid Conferences
      if (!(conference %in% validConfs)) {
        message("Invalid Conference Input")
        message("Valid Conference Input includes ...")
        return(validConfs)
      }
      # Vector of teams in conference
      confTeams = teamData %>% subset(., Conference == conference, select = School) %>% 
                              unlist(use.names = FALSE)
      return(confTeams)
    },
    error=function(e) {
      message('An Error Occurred')
      print(e)
      print(cat("Conference =", conference))
    },
    warning=function(w) {
      message('A Warning Occurred')
      print(w)
      print(cat("Conference =", conference))
      return(NA)
    }
  )
}
```

Testing
```{r}
teamData = getAllTeams()
print(getConferenceTeams(teamData, conference = "PAC"))
```

