---
title: "getNicknameTeam"
author: "Jordan Gilbert, Marion Haney"
date: '2023-02-15'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
require(rje)
require(dplyr)
require(assertthat)
```

getNicknameTeam:
INPUT: 
teamData: the output of getAllTeams
nickname: the string nickname to search for
OUTPUT: vector containing the string names of all the D3 football teams
who go by the given nickname
DEFAULT: nickname = "Tartans"

```{r}
getNicknameTeam = function(teamData, nickname = "Tartans") {
  tryCatch(
    {
      validNick = sort(unique(teamData$Nickname))
      
      # Check if string input
      if (!(is.string(nickname))) {
        message("Invalid Nickname Input")
        message("Valid Nickname Input includes ...")
        return(validNick)
      }
      
      # Check if nickname input is a valid nickname
      if (!(nickname %in% validNick)) {
        message("Invalid Nickname Input")
        message("Valid Nickname Input includes ...")
        return(validNick)
      }
      
      # Vector of teams with nickname
      nicknameTeams = teamData %>% subset(., Nickname %in% nickname, select = School) %>% unlist(use.names = FALSE)
      return(nicknameTeams)
    },
    error=function(e) {
      message('An Error Occurred')
      print(e)
      print(cat("Nickname =", nickname))
    },
    warning=function(w) {
      message('A Warning Occurred')
      print(w)
      print(cat("Nickname =", nickname))
      return(NA)
    }
  )
}
```


Testing
```{r}
teamData = getAllTeams()
print(getNicknameTeam(teamData, nickname = "Bulldogs"))
print(getNicknameTeam(teamData, nickname = "Spartans"))
```
