---
title: "getRegionTeams"
author: "Jordan Gilbert, Marion Haney"
date: '2023-02-15'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
require(rje)
require(dplyr)
```

getRegionTeams:
INPUT: 
teamData: the output of getAllTeams
region: the integer representing the region
OUTPUT: vector containing the string names of all the D3 football teams
in the specified region
DEFAULT: region = 2

```{r}
getRegionTeams = function(teamData, region = 2) {
  tryCatch(
    {
      validRegions = sort(unique(teamData$Region))
      
      # Check if numeric input
      if (!(is.numeric(region))) {
        message("Invalid Region Input")
        message("Valid Region Input includes ...")
        return(validRegions)
      }
      
      # Check if region input is a valid region
      if (!(region %in% validRegions)) {
        message("Invalid Region Input")
        message("Valid Region Input includes ...")
        return(validRegions)
      }
      
      # Vector of teams in region
      regionalTeams = teamData %>% subset(., Region == region, select = School) %>% unlist(use.names = FALSE)
      return(regionalTeams)
    },
    error=function(e) {
      message('An Error Occurred')
      print(e)
      print(cat("Region =", region))
      return(NA)
    },
    warning=function(w) {
      message('A Warning Occurred')
      print(w)
      print(cat("Region =", region))
      return(NA)
    }
  )
}
```

Testing
```{r}
teamData = getAllTeams()
print(getRegionTeams(teamData, region = 2))
```
