---
title: "getSurfaceTeams"
author: "Jordan Gilbert, Marion Haney"
date: '2023-02-15'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rvest)
require(magrittr)
require(stringr)
require(rje)
require(dplyr)
```

getSurfaceTeams:
INPUT: 
teamData: the output of getAllTeams
surface: the string of the surface type
OUTPUT: vector containing the string names of all the D3 football teams
who play on the specified surface
DEFAULT: surface = "Turf"

```{r}
getSurfaceTeams = function(teamData, surface = "Turf") {
  tryCatch(
    {
      validSurface = sort(unique(teamData$Surface))
      
      # Check if string input
      if (!(is.string(surface))) {
        message("Invalid Surface Input")
        message("Valid Surface Input includes ...")
        return(validSurface)
      }
      
      # Check if surface input is a valid surface
      if (!(surface %in% validSurface)) {
        message("Invalid Surface Input")
        message("Valid Surface Input includes ...")
        return(validSurface)
      }
      
      # Vector of teams by field surface type
      surfaceTeams = teamData %>% subset(., Surface == surface, select = School) %>% unlist(use.names = FALSE)
      return(surfaceTeams)
    },
    error=function(e) {
      message('An Error Occurred')
      print(e)
      print(cat("Surface =", surface))
    },
    warning=function(w) {
      message('A Warning Occurred')
      print(w)
      print(cat("Surface =", surface))
      return(NA)
    }
  )
}
```

Testing
```{r}
teamData = getAllTeams()
print(getSurfaceTeams(teamData, surface = "Turf"))
```

