---
title: "Graphing"
author: "Jordan Gilbert"
date: "2023-03-20"
output: pdf_document
---

```{r}
# Libraries
require(ggplot2)
```

```{r}
#data = read.csv("Web\\Scraping/PAC-20220-pbp.csv")
data = read.csv("./PAC-2022-cleaned-pbp-wEPA.csv")
```

```{r}
# D3 Scoring Plays
TeamScored = subset(data, Points.Scored. == TRUE)
TeamScored$Distance.to.Touchdown = as.numeric(TeamScored$Distance.to.Touchdown)
TeamScored$Down = as.factor(TeamScored$Down)

TeamScoredTD = subset(TeamScored, Touchdown. == TRUE)
TeamScoredFG = subset(TeamScored, Field.Goal. == TRUE)

ggplot(TeamScored) +
  geom_histogram(aes(Distance.to.Touchdown), binwidth = 5, color = "black", fill = "cornflowerblue") +
  labs(title = "Histogram of Distance to Goal for Scoring Play", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")

ggplot(TeamScoredTD) +
  geom_histogram(aes(Distance.to.Touchdown), binwidth = 5, color = "black", fill = "cornflowerblue") +
  labs(title = "Histogram of Distance to Goal for Touchdown Scoring Play", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")

ggplot(TeamScoredFG) +
  geom_histogram(aes(Distance.to.Touchdown), binwidth = 5, color = "black", fill = "cornflowerblue") +
  labs(title = "Histogram of Distance to Goal for Field Goal Scoring Play", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")
```
```{r}
# CMU Offensive of Plays
CMUOffense = subset(data, Team.Possession == "Carnegie Mellon")
CMUOffense$Distance.to.Touchdown = as.numeric(CMUOffense$Distance.to.Touchdown)
CMUOffense$Down = as.factor(CMUOffense$Down)

CMUOffenseScored = subset(CMUOffense, Points.Scored. == TRUE)
CMUOffenseScoredTD = subset(CMUOffenseScored, Touchdown. == TRUE)
CMUOffenseScoredFG = subset(CMUOffenseScored, Field.Goal. == TRUE)

ggplot(CMUOffenseScoredTD) +
  geom_histogram(aes(Distance.to.Touchdown), binwidth = 5, color = "black", fill = "red") +
  labs(title = "Histogram of Distance to Goal for CMU Offense Scoring Touchdown", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")

ggplot(CMUOffenseScoredFG) +
  geom_histogram(aes(Distance.to.Touchdown), binwidth = 5, color = "black", fill = "red") +
  labs(title = "Histogram of Distance to Goal for CMU Offense Scoring Field Goal", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")
```

```{r}
data = read.csv("PAC-2022-cleaned-pbp-wEPA.csv")

# Make categorical variables
data$Next_Score_Half = as.factor(data$Next_Score_Half)
data$Drive_Outcome = as.factor(data$Drive_Outcome)
data$Quarter = as.factor(data$Quarter)
data$Down = as.factor(data$Down)
```

```{r}
# Line Graph
ggplot(data, aes(x = Distance.to.Touchdown, y = EP, color = Down)) +
  geom_line() +
  scale_x_reverse()
```

```{r}
# Line Graph
ggplot(data, aes(x = Distance.to.Touchdown, y = EP, color = Down)) +
  geom_smooth() +
  scale_x_reverse() +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 20, color = "red", lty = 2) +
  labs(title = "Change in Expected Points by Down (PAC)", x = "Distance to Opponent's Touchdown",
       y = "Expected Points (EP)") +
  theme_bw() +
  ylim(-3.5, 7.5)
```

```{r}
# Line Graph
ggplot(data, aes(x = Distance.to.Touchdown)) +
  geom_smooth(aes(y = Touchdown_Prob), fill = "pink") +
  geom_smooth(aes(y = Field_Goal_Prob)) +
  scale_x_reverse() +
  geom_hline(yintercept = 0) +
  labs(title = "Expected Points Chart of PAC Teams", x = "Distance to Opponent's Touchdown",
       y = "Expected Points (EP)")
```

```{r}
# Line Graph
data %>%
  select(Distance.to.Touchdown, Touchdown_Prob, Field_Goal_Prob) %>% 
  pivot_longer(cols = c(Touchdown_Prob, Field_Goal_Prob)) %>%
  ggplot(aes(x = Distance.to.Touchdown, y = value,color = fct_relevel(name, "Touchdown_Prob", "Field_Goal_Prob"))) +
  geom_smooth() +
  scale_x_reverse() +
  labs(title = "Probability of Scoring Outcome (PAC)", x = "Distance to Opponent's Touchdown",
       y = "Probability of Outcome Occuring", color = "Scoring Outcome") +
  scale_color_hue(labels = c("Touchdown Percentage", "Field Goal Percentage")) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw()
```

```{r}
data %>% 
  group_by(Down) %>% 
  summarize(mean = mean(EP, na.rm = TRUE), std.dev = sd(EP, na.rm = TRUE),
            median = median(EP, na.rm = TRUE)) %>% 
  round(2)
```


```{r}
# Line Graph
data %>%
  select(Distance.to.Touchdown, Touchdown_Prob, Field_Goal_Prob) %>% 
  pivot_longer(cols = c(Touchdown_Prob, Field_Goal_Prob)) %>%
  ggplot(aes(x = Distance.to.Touchdown, y = value, fill = name)) +
  stat_smooth(geom = 'area', position = "stack", alpha = 1/2) +
  scale_x_reverse() +
  labs(title = "Probability of Scoring - CMU", x = "Distance to Opponent's Touchdown",
       y = "Probability of Outcome", fill = "Scoring Outcome") +
  scale_fill_hue(labels = c('Field Goal Percentage', 'Touchdown Percentage'))
```


```{r}
# Density Graph
ggplot(data, aes(x = Distance.to.Touchdown, y = EP)) +
  geom_density()
```

