---
title: "Modeling-ScrapedData-Jordan"
author: "Jordan Gilbert"
date: "2023-04-03"
output: pdf_document
---

```{r}
# Libraries
require(ggplot2)
require(tidyverse)
require(dplyr)
require(nnet)
require(tidyr)
```

```{r}
# Read in data
data = read.csv("PAC-2022-pbp3.csv")
data = filter(data, rowSums(is.na(data)) != ncol(data))
```

Helper function that takes in the current play index, a vector of the scoring play indices, and play-by-play data and returns the score type and drive number for the next score
```{r}
FindNextScore = function(play_index, scoring_plays, data) {
  # next score index
  next_score_index = scoring_plays[which(scoring_plays >= play_index)[1]]
  
  # if next score index has no more scores after the current play
  if (is.na(next_score_index) | (data$Quarter[play_index] %in% c("1st", "2nd") & data$Quarter[next_score_index] %in% c("3rd", "4th")) | (data$Quarter[play_index] %in% c("3rd", "4th") & data$Quarter[next_score_index] %in% c("1st", "2nd", "OT"))) {
    score_type = "No_Score"
    score_drive = data$Drive.Number[play_index]
  } 
  # else return the observed next score type and drive number
  else {
    # score drive number
    score_drive = data$Drive.Number[next_score_index]
    
    # TD
    if (data$Points.Scored.[next_score_index] & data$Touchdown.[next_score_index]) {
      # check who scored touchdown
      # look at extra point to know who scored
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index + 1])) {
        score_type = "Opp_Touchdown"
      }
      else {
        score_type = "Touchdown"
      }
    }
    # FG
    else if (data$Points.Scored.[next_score_index] & data$Field.Goal.[next_score_index]) {
      # check who scored field goal
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index])) {
        score_type = "Opp_Field_Goal"
      }
      else{
        score_type = "Field_Goal"
      }
    }
    # Extra Point
    else if (data$Points.Scored.[next_score_index] & data$Extra.Point.[next_score_index]) {
      # check who scored extra point
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index])) {
        score_type = "Opp_Extra_Point"
      }
      else {
        score_type = "Extra_Point"
      }
    }
    # Safety
    else if (data$Points.Scored.[next_score_index] & data$Safety.[next_score_index]) {
      # check who scored safety
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index + 1])) {
        score_type = "Opp_Safety"
      }
      else {
        score_type = "Safety"
      }
    }
    # Error
    else {
      score_type = NA
    }
  }
  return(data.frame(Next_Score_Half = score_type,
                    Drive_Score_Half = score_drive))
}
```


```{r}
# Which rows are the scoring plays
scoring_plays = which(data$Points.Scored.)
```


```{r}
next_score = lapply(c(1:nrow(data)), FindNextScore, scoring_plays = scoring_plays, data = data) %>% bind_rows()
data = cbind(data, next_score)
```

Drive Outcome
```{r}
GetDriveOutcome = function(play_index, last_play_of_drive, data) {
  # next score index
  curr_last_play_index = last_play_of_drive[which(last_play_of_drive >= play_index)[1]]
  
  #last_play_of_drive_type = data$Outcome
  
  if (is.na(curr_last_play_index)) {
    drive_outcome = "Time Expired"
  }
  else {
    
    # TD scored
    if (data$Touchdown.[curr_last_play_index] | data$Extra.Point.[curr_last_play_index] |
        data$Touchdown.[curr_last_play_index - 1]) {
      drive_outcome = "Touchdown"
    }
    # FG scored
    else if (data$Field.Goal.[curr_last_play_index]) {
      drive_outcome = "Field Goal"
    }
    # Safety Scored
    else if (data$Safety.[curr_last_play_index]) {
      drive_outcome = "Safety"
    }
    # Punt
    else if (data$Punt.[curr_last_play_index]) {
      drive_outcome = "Punt"
    }
    # Turnover
    else if (data$Turnover.[curr_last_play_index] | data$Turnover.[curr_last_play_index + 1]) {
      drive_outcome = "Turnover"
    }
    # Turnover on Downs
    else if (data$Down[curr_last_play_index] == 4) {
      drive_outcome = "Turnover on Downs"
    }
    # Time expired
    else {
      drive_outcome = "Time Expired"
    }
  }
  return(data.frame(Drive_Outcome = drive_outcome))
}
```


```{r}
# switch of possession, hence end of drive
first_play_of_drive = which(data$Team.Possession != lag(data$Team.Possession))
last_play_of_drive = first_play_of_drive - 1
```

```{r}
drive_outcome = lapply(c(1:nrow(data)), GetDriveOutcome, last_play_of_drive = last_play_of_drive, data = data) %>%
  bind_rows()
data = cbind(data, drive_outcome)
```

```{r}
# add information of where drive started
# initiate new column
data["Drive.Starting.Distance.to.Touchdown"] = data$Distance.to.Touchdown
# first drive
data$Drive.Starting.Distance.to.Touchdown[1:(head(first_play_of_drive, 1) - 1)] = data$Distance.to.Touchdown[1]
for (i in 1:(length(first_play_of_drive) - 1)) {
  (data$Drive.Starting.Distance.to.Touchdown[first_play_of_drive[i]:(first_play_of_drive[i + 1] - 1)] = data$Distance.to.Touchdown[first_play_of_drive[i]])
}
```

```{r}
# add information of net yards
#data["Net.Yards"] = c(rollapply(data$Distance.to.Touchdown, width = 2, function(x) {x[1] - x[2]}, fill = 0))
net.yards = (data %>% group_by(Team.Possession, Drive.Number) %>% mutate(diff = lag(Distance.to.Touchdown,
              default = first(Distance.to.Touchdown)) - Distance.to.Touchdown))$diff
net.yards = tail(net.yards, -1)
net.yards = c(net.yards, 0)
data["Net.Yards"] = net.yards
# Note: end of drive (punt, turnover touchdown, set to zero net yards)
# Change for touchdown
data$Net.Yards[data$Touchdown.] = data$Distance.to.Touchdown[data$Touchdown.]
```

Quarters to Half
```{r}
data$Half <- with(data, ifelse(Quarter %in% c("1st", "2nd"), "1st", "2nd"))
```

Modeling
```{r}
# Next Score Multinomial Regression

# Refactor
#data_noEP = data %>% subset(!Extra.Point.)
data_noEP = data[data$Next_Score_Half %in% c("Field_Goal", "Opp_Field_Goal", "Touchdown", "Opp_Touchdown",
                                             "No_Score"), ]
data_noEP = data_noEP %>% droplevels() %>% mutate(Next_Score_Half = 
                         fct_relevel(Next_Score_Half, "No_Score")) 

# Make yards to go variable
data_noEP$Yards.to.Go = as.numeric(ifelse(data_noEP$Distance.to.First.Down ==
        "Goal", data_noEP$Distance.to.Touchdown, data_noEP$Distance.to.First.Down))

# Make is Down and Goal variable
data_noEP$is.Goal.Down <- ifelse(data_noEP$Distance.to.First.Down == "Goal",
                          1, 0)

# Make Game ID variable
data_noEP = data_noEP %>% unite("Game.ID", c(Date, Home.Team.Abbreviation, Away.Team.Abbreviation))

```

```{r}
# Y: df$Next_Score_Half
# X: df$Down, log(df$Distance.to.Touchdown)
ep.model <- multinom(factor(Next_Score_Half) ~ 
                             factor(Down)
                           + log(Yards.to.Go)
                           + Distance.to.Touchdown
                           + factor(is.Goal.Down)
                           + factor(Down):log(Yards.to.Go), 
                           data = data_noEP, maxit = 300)
summary(ep.model)
```

```{r}
init_loso_cv_preds <- map_dfr(unique(data_noEP), 
          function(x) {
            # Separate test and training data:
            ## 75% of the sample size
            smp_size <- floor(0.75 * nrow(data_noEP))
            set.seed(1)
            train_ind <- sample(seq_len(nrow(data_noEP)), size = smp_size)
            train_data <- data_noEP[train_ind, ]
            test_data <- data_noEP[-train_ind, ]
            
            # Fit multinomial logistic regression model:
            ep_model <- multinom(factor(Next_Score_Half) ~ 
                             factor(Down)
                           + log(Yards.to.Go)
                           + Distance.to.Touchdown
                           + factor(is.Goal.Down)
                           + factor(Down):log(Yards.to.Go), 
                           data = data_noEP, maxit = 300)
            
            # Return dataset of class probabilities:
            predict(ep_model, newdata = test_data, type = "probs") %>%
              as_tibble() %>%
              mutate(Next_Score_Half = test_data$Next_Score_Half)
            })
```

```{r}
ep_cv_loso_calibration_results <- init_loso_cv_preds %>%
  pivot_longer(No_Score:Opp_Touchdown,
               names_to = "next_score_type",
               values_to = "pred_prob") %>%
  mutate(bin_pred_prob = round(pred_prob / 0.05) * .05) %>%
  group_by(next_score_type, bin_pred_prob) %>%
  summarize(n_plays = n(), 
            n_scoring_event = length(which(Next_Score_Half == next_score_type)),
            bin_actual_prob = n_scoring_event / n_plays,
            bin_se = sqrt((bin_actual_prob * (1 - bin_actual_prob)) / n_plays)) %>%
  ungroup() %>%
  mutate(bin_upper = pmin(bin_actual_prob + 2 * bin_se, 1),
         bin_lower = pmax(bin_actual_prob - 2 * bin_se, 0))
```

```{r}
ep_cv_loso_calibration_results <- na.omit(ep_cv_loso_calibration_results)
ep_cv_loso_calibration_results %>%
  mutate(next_score_type = fct_relevel(next_score_type, "No_Score", "Field_Goal", 
                                       "Opp_Field_Goal", "Touchdown", "Opp_Touchdown"),
  next_score_type = fct_recode(next_score_type,
                               "No_Score (0)" = "No_Score", 
                               "Field_Goal (3)" = "Field_Goal",
                               "Opp_Field_Goal (-3)" = "Opp_Field_Goal",
                               "Touchdown (7)" = "Touchdown",
                               "Opp_Touchdown (-7)" = "Opp_Touchdown")) %>%
  ggplot(aes(x = bin_pred_prob, y = bin_actual_prob)) +
  geom_abline(slope = 1, intercept = 0, color = "black", linetype = "dashed") +
  geom_smooth(se = FALSE) + 
  geom_point(aes(size = n_plays)) +
  geom_errorbar(aes(ymin = bin_lower, ymax = bin_upper)) + #coord_equal() +   
  scale_x_continuous(limits = c(0,1)) + 
  scale_y_continuous(limits = c(0,1)) + 
  labs(size = "Number of plays", x = "Estimated next score probability", 
       y = "Observed next score probability") + 
  theme_bw() + 
  theme(strip.background = element_blank(), 
        axis.text.x = element_text(angle = 90), 
        legend.position = c(1, .05), legend.justification = c(1, 0)) +
  facet_wrap(~ next_score_type, ncol = 4)
```


```{r}
# Class Probabilities
class_prob = predict(ep_model, data_noEP, type = "probs") %>% as_tibble() %>% 
              mutate(Next_Score_Half = data_noEP$Next_Score_Half)

```



Graphics
```{r}
# Make categorical variables
data$Next_Score_Half = as.factor(data$Next_Score_Half)
data$Drive_Outcome = as.factor(data$Drive_Outcome)
data$Quarter = as.factor(data$Quarter)
data$Down = as.factor(data$Down)
```

```{r}
ggplot(data, aes(x = Drive_Outcome, fill = Down)) +
  geom_bar() +
  labs(title = "Stacked Bar Plot of Drive Outcome by Down", x = " Drive Outcome") +
  geom_text(stat = "count", aes(label = ..count..), size = 3, position = position_stack(vjust = 0.5)) +
  scale_fill_brewer()
```

```{r}
ggplot(data, aes(x = Next_Score_Half, fill = Down)) +
  geom_bar() +
  labs(title = "Stacked Bar Plot of Next Score Event by Down", x = " Next Score Event") +
  geom_text(stat = "count", aes(label = ..count..), size = 3, position = position_stack(vjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90)) 
```

Save the cleaned data
```{r}
write.csv(data, "PAC-2022-Cleaned-pbp.csv", row.names=FALSE)
```


```{r}
# group_by(data, id)
# 
ggplot(data) +
  geom_boxplot(aes(Drive.Starting.Distance.to.Touchdown, Drive_Outcome, fill = Drive_Outcome)) +
  labs(title = "Boxplot of Outcome based on Starting Distance to Touchdown of Drive", y = "Drive Outcome",
       x = "Distance to Touchdown at Start of Drive")
```


```{r}
ggplot(data) +
  geom_point(aes(x = Distance.to.Touchdown, y = Drive_Outcome, color = Drive_Outcome))
```

```{r}
# D3 Scoring Plays
TeamScored = subset(data, Points.Scored. == TRUE)
TeamScored$Down = as.factor(TeamScored$Down)

TeamScoredTD = subset(TeamScored, Touchdown. == TRUE)
TeamScoredFG = subset(TeamScored, Field.Goal. == TRUE)

ggplot(TeamScored) +
  geom_histogram(aes(Drive.Starting.Distance.to.Touchdown), binwidth = 5, color = "black", fill = "cornflowerblue") +
  labs(title = "Histogram of Drive Starting Distance to Endzone for Scoring Play", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")

ggplot(TeamScoredTD) +
  geom_histogram(aes(Drive.Starting.Distance.to.Touchdown), binwidth = 5, color = "black", fill = "cornflowerblue") +
  labs(title = "Histogram of Drive Starting Distance to Endzone for Touchdown Scoring Play", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")

ggplot(TeamScoredFG) +
  geom_histogram(aes(Drive.Starting.Distance.to.Touchdown), binwidth = 5, color = "black", fill = "cornflowerblue") +
  labs(title = "Histogram of Drive Starting Distance to Endzone for Field Goal Scoring Play", x = "Distance to Goal",
       subtitle = "Binwidth = 5 yards")
```

```{r}
ggplot(TeamScoredTD) +
  geom_point(aes(Drive.Starting.Distance.to.Touchdown, Distance.to.Touchdown, color = Drive_Outcome))
```

```{r}
ggplot(data) +
  geom_boxplot(aes(Net.Yards, fill = Down))
```

```{r}
ggplot(data) +
  geom_density(aes(Drive.Starting.Distance.to.Touchdown, color = Next_Score_Half))
```

```{r}
ggplot(data) +
  geom_density(aes(Distance.to.Touchdown, color = Next_Score_Half))
```


```{r}
data %>% group_by(Team.Possession, Down, Net.Yards)
```

