---
title: "Model-ScrapedData"
author: "Jordan Gilbert"
date: "2023-03-21"
output: pdf_document
---

```{r}
# Libraries
require(ggplot2)
require(tidyverse)
require(dplyr)
```

```{r}
# Read in data
data = read.csv("PAC-2022-pbp2.csv")
```

Helper function that takes in the current play index, a vector of the scoring play indices, and play-by-play data and returns the score type and drive number for the next score
```{r}
FindNextScore = function(play_index, scoring_plays, data) {
  # next score index
  next_score_index = scoring_plays[which(scoring_plays >= play_index)[1]]
  
  # if next score index has no more scores after the current play
  if (is.na(next_score_index) | (data$Quarter[play_index] %in% c("1st", "2nd") & data$Quarter[next_score_index] %in% c("3rd", "4th")) | (data$Quarter[play_index] %in% c("3rd", "4th") & data$Quarter[next_score_index] %in% c("1st", "2nd", "OT"))) {
    score_type = "No Score"
    score_drive = data$Drive.Number[play_index]
  } 
  # else return the observed next score type and drive number
  else {
    # score drive number
    score_drive = data$Drive.Number[next_score_index]
    
    # TD
    if (data$Points.Scored.[next_score_index] & data$Touchdown.[next_score_index]) {
      # check who scored touchdown
      # look at extra point to know who scored
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index + 1])) {
        score_type = "Opp_Touchdown"
      }
      else {
        score_type = "Touchdown"
      }
    }
    # FG
    else if (data$Points.Scored.[next_score_index] & data$Field.Goal.[next_score_index]) {
      # check who scored field goal
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index])) {
        score_type = "Opp_Field_Goal"
      }
      else{
        score_type = "Field_Goal"
      }
    }
    # Extra Point
    else if (data$Points.Scored.[next_score_index] & data$Extra.Point.[next_score_index]) {
      # check who scored extra point
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index])) {
        score_type = "Opp_Extra_Point"
      }
      else {
        score_type = "Extra_Point"
      }
    }
    # Safety
    else if (data$Points.Scored.[next_score_index] & data$Safety.[next_score_index]) {
      # check who scored safety
      if (!identical(data$Team.Possession[play_index], data$Team.Possession[next_score_index + 1])) {
        score_type = "Opp_Safety"
      }
      else {
        score_type = "Safety"
      }
    }
    # Error
    else {
      score_type = NA
    }
  }
  return(data.frame(Next_Score_Half = score_type,
                    Drive_Score_Half = score_drive))
}
```


```{r}
# Which rows are the scoring plays
scoring_plays = which(data$Points.Scored.)
```


```{r}
next_score = lapply(c(1:nrow(data)), FindNextScore, scoring_plays = scoring_plays, data = data) %>% bind_rows()
data = cbind(data, next_score)
```

Drive Outcome
```{r}
GetDriveOutcome = function() {
  last_play_of_drive = which(data$Team.Possession != lag(data$Team.Possession))
  last_play_of_drive = last_play_of_drive - 1
  #last_play_of_drive_type = data$Outcome
  index = 1
  curr_last_play_index = last_play_of_drive[index]
  drive_outcome = c()
  for (curr_play in 1:length(last_play_of_drive)) {
    if (curr_play_index <= curr_last_play_index) {
      if (data$Touchdown.[curr_last_play_index]) {
        drive_outcome = append(drive_outcome, "")
      }
    }
  }
}
```


Quarters to Half
```{r}
## take away that weird NA row in the beginning
# data <- slice(data, -1)
data$Half <- with(data, ifelse(Quarter %in% c("1st", "2nd"), "1st", "2nd"))
```





